---
title: "Final Report"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-2)
author: "Miracle Ramos"
pagetitle: "Final Project Miracle Ramos"
date: today

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin
---



::: {.callout-tip icon=false}

## Github Repo Link

[Miracle's GitHub Repo Link (miracleramos2025)](https://github.com/stat301-2-2025-winter/final-project-2-miracleramos2025.git)

:::

## Executive Summary 

The purpose of this report is to develop a predictive model for forecasting Airbnb rental prices in New York City. Using a dataset from Kaggle that includes listing details, host characteristics, location data, and pricing metrics, this analysis explores the key factors that influence short term rental prices and evaluates different machine learning models to improve price predictions.

The results show that the Linear Model performed best and achieved the lowest RMSE of 188.7 while maintaining interpretability. Surprisingly, more complex models like Random Forest and Boosted Trees did not significantly outperform the simpler linear regression model. This suggests that Airbnb prices may be largely determined by structured factors such as location, room type, and availability, which align well with linear assumptions.

Feature engineering played a key role in the modeling process with transformations such as one-hot encoding for categorical variables, median imputation for missing values, and log transformation of price improving model stability. Hyperparameter tuning further optimized performance, particularly for k-Nearest Neighbors (k = 44) and Elastic Net even though these models did not surpass the linear model in predictive accuracy.

Despite the model’s effectiveness at capturing general price trends, limitations still remain. The low R² value of 13.4% suggests that additional features like seasonality, demand surges, and listing-specific amenities could improve predictive power. Luxury or high-end Airbnb listings were often underpredicted which indicates that luxury properties may have unique pricing dynamics that were not captured by the available data.

In conclusion, while the Linear Model provides a simple and interpretable pricing estimate, additional work is needed to enhance predictive accuracy for higher priced listings. Future improvements could include incorporating temporal data, using geographic proximity features, and exploring more advanced tree-based models with refined hyperparameter tuning. This analysis offers valuable insights into what drives Airbnb pricing in NYC and provides a foundation for both hosts and guests to better understand market trends.








